# Generated by Django 3.2.6 on 2021-09-07 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessonsets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='image',
        ),
        migrations.RemoveField(
            model_name='person',
            name='url_page',
        ),
    ]
