# Generated by Django 3.2.6 on 2021-09-08 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessonsets', '0004_auto_20210908_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='team',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
